name: csl
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - comm=0.2.3
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.1
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=8.18.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - libedit=3.1.20250104
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - libkrb5=1.21.3
  - libsodium=1.0.20
  - libstdcxx=15.1.0
  - libstdcxx-ng=11.2.0
  - libxcb=1.17.0
  - lmdb=0.9.31
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.5.2
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.1
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.9.23
  - python-dateutil=2.9.0.post0
  - python_abi=3.9
  - pyzmq=27.0.1
  - readline=8.2
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.14.1
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - antlr4-python3-runtime==4.8
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - array-record==0.5.1
      - arrow==1.4.0
      - astunparse==1.6.3
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.3.0
      - audiomentations==0.41.0
      - audioread==3.0.1
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.2.0
      - bokeh==2.4.3
      - certifi==2025.8.3
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - chex==0.1.90
      - click==8.1.8
      - cloudpickle==3.1.2
      - cmake==3.25.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - cython==3.1.3
      - defusedxml==0.7.1
      - distrax==0.1.5
      - dm-tree==0.1.8
      - essentia==2.1b6.dev1034
      - etils==1.5.2
      - fastjsonschema==2.21.2
      - filelock==3.13.1
      - flatbuffers==25.9.23
      - fonttools==4.59.0
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2025.7.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.14.0
      - hf-xet==1.1.7
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.10
      - importlib-resources==6.5.2
      - intervaltree==3.1.0
      - isoduration==20.11.0
      - jams==0.3.5
      - jax==0.4.30
      - jaxlib==0.4.30
      - jinja2==3.1.4
      - joblib==1.5.1
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterthemes==0.20.0
      - keras==3.10.0
      - kiwisolver==1.4.7
      - lark==1.3.1
      - lazy-loader==0.4
      - lesscpy==0.15.1
      - libclang==18.1.1
      - librosa==0.10.2.post1
      - lightning-utilities==0.15.2
      - linkify-it-py==2.0.3
      - lit==15.0.7
      - llvmlite==0.43.0
      - markdown==3.9
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - miditok==3.0.6
      - mido==1.3.3
      - mir-eval==0.8.2
      - mistune==3.1.4
      - ml-dtypes==0.5.3
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.7.0
      - namex==0.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.2.1
      - note-seq==0.0.5
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numpy==1.26.3
      - numpy-minmax==0.3.1
      - numpy-rms==0.4.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.1.1
      - opt-einsum==3.4.0
      - optax==0.2.4
      - optree==0.18.0
      - overrides==7.7.0
      - pandas==2.3.1
      - pandocfilters==1.5.1
      - panel==1.4.5
      - param==2.2.1
      - pedalboard==0.9.17
      - pillow==11.3.0
      - ply==3.11
      - pooch==1.8.2
      - pretty-midi==0.2.9
      - prometheus-client==0.23.1
      - promise==2.3
      - propcache==0.4.1
      - protobuf==6.33.1
      - pybind11==3.0.1
      - pycparser==2.22
      - pydub==0.25.1
      - pyfluidsynth==1.3.0
      - pyparsing==3.2.3
      - pyroomacoustics==0.8.4
      - pysmartdl==1.3.4
      - python-json-logger==4.0.0
      - python-stretch==0.3.1
      - pytorch-fast-transformers==0.4.0
      - pytorch-lightning==1.8.4
      - pytz==2025.2
      - pyviz-comms==3.0.6
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2025.11.3
      - requests==2.32.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rpds-py==0.26.0
      - sacremoses==0.1.1
      - safetensors==0.7.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soundfile==0.13.1
      - soupsieve==2.8
      - soxr==0.5.0.post1
      - sympy==1.13.3
      - symusic==0.5.8
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - tensorflow==2.20.0
      - tensorflow-datasets==4.9.3
      - tensorflow-metadata==1.17.2
      - tensorflow-probability==0.25.0
      - termcolor==3.1.0
      - terminado==0.18.1
      - tf-keras==2.20.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tokenizers==0.22.1
      - toml==0.10.2
      - tomli==2.3.0
      - toolz==1.1.0
      - torch==2.8.0+cu128
      - torchaudio==2.8.0
      - torchmetrics==1.8.2
      - torchvision==0.23.0+cu128
      - tqdm==4.67.1
      - transformers==4.57.3
      - triton==3.4.0
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - uc-micro-py==1.0.3
      - uri-template==1.3.0
      - urllib3==2.5.0
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.3
      - wrapt==2.0.1
      - xyzservices==2025.10.0
      - yarl==1.22.0
      - yt-dlp==2025.10.14
prefix: /home/emiliopicard/miniconda3/envs/csl
